package com.example.chordtrain.db

import androidx.lifecycle.LiveData
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Transaction

@Dao
interface StatisticsDao {
    //Conflict unlikely to happen given autogenerated keys but included it just to be sure
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAttempt(attempt: Attempt): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertChords(chords: List<AttemptChord>)


    @Transaction
    @Query("SELECT * FROM attempt ORDER BY attemptId DESC")
    fun getAllAttemptsWithChords(): LiveData<List<AttemptWithChords>>
}
